services:
  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: app
    image: go-gin
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/backend