services:
  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: app
    image: go-gin
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/backend
  db:
    image: mysql:9.3
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306